---
abstract: 'Interface to the London Tube Map.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Module::Build: 0.36
  Readonly: 0
  Test::More: 0
  Time::HiRes: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Travel-UK-London-Tube
provides:
  Travel::UK::London::Tube:
    file: lib/Travel/UK/London/Tube.pm
    version: 0.01
  Travel::UK::London::Tube::Node:
    file: lib/Travel/UK/London/Tube/Node.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
